version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CloudWatch-Kinesis-Lambda-Processor"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppBucketName=\"\""
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6negvx3aoqaw"
s3_prefix = "CloudWatch-Kinesis-Lambda-Processor"
